name: ftmithaimart
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_swipable:
  shared_preferences: ^2.2.2
  flutter_carousel_widget: ^2.1.2
  mongo_dart: ^0.9.3
  fluttertoast: ^8.2.4
  animated_splash_screen: ^1.3.0
  firebase_core: ^2.24.2
  firebase_analytics: ^10.6.3
  provider: ^6.0.5
  sqflite: ^2.3.0
  http: ^1.1.0
  firebase_messaging: ^14.7.9
  flutter_local_notifications: ^16.2.0
  google_sign_in: ^6.2.1
  firebase_auth: ^4.16.0
  permission_handler: ^11.1.0
  intl: ^0.19.0
  dio: ^5.4.1
  flutter_launcher_icons: ^0.13.1
  otp: ^3.1.4
  image_picker: ^1.0.7
  url_launcher: ^6.2.5
  otp_pin_field: ^1.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/Logo.png
    - assets/google.png
    - assets/splash.png
    - assets/countrycodes.json


fonts:
  family: Montserrat
  fonts:
    -fonts/Montserrat-Italic-VariableFont_wght.ttf
    -fonts/Montserrat-VariableFont_wght.ttf
    -fonts/Montserrat-Regular.ttf






