name: ftmithaimart
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  flutter:
    sdk: flutter
  flutter_swipable:
  shared_preferences: ^2.2.2
  flutter_carousel_widget: ^2.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/Logo.png


fonts:
  -family: Montserrat
  fonts:
    -fonts/Montserrat-Italic-VariableFont_wght.ttf
    -fonts/Montserrat-VariableFont_wght.ttf
    -fonts/Montserrat-Regular.ttf






